### ISSUE TITLE
Zero cost orders will still ask for a payment

### ISSUE THREAD

**Issue by brucewyne** [VividWeb/vivid_store#1]
If an order/tax/shipping total is 0, we're still asking for a credit card. Womp womp.

**Comment by Mesuva** [comment]
A suggestion here is that each gateway could support something a validAmount function, so it only makes itself available as a payment option if it passes whatever tests this function would have. 

Some gateways such as Stripe have a minimum value of 50c.

This would also support a gateway for 'free order' (i.e discount codes reduce the price to zero for example), while gateways for non-transaction methods like EFT and Cheques could have this value set to something very low but non-zero. 

The function could then also refer to config values. People might want to accept cheques, but only over a certain amount.

(trying not to over complicate this though!)
