### ISSUE TITLE
Product attributes not being stored/display in cart or on product lists

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#104]
Although product options are appearing on product pages, they're not appearing elsewhere, and they don't appear to be stored against items in the cart.

**Comment by brucewyne** [comment]
So this seems to be a new issue. If you look at the cart single page, you can see where this was suppose to showing. The OrderItem class is even adding them. I think this is getting screwed up somewhere when it gets added to the cart. It's not sending the product options data.
