### ISSUE TITLE
Product needs max quantity option and/or option to make product non-physical (limited to 1 with no option to change quantity in cart)

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#117]

**Comment by brucewyne** [comment]
Non physical doesn't necessarily mean just one though. Example: licenses. But I'm into making everything optional.

**Comment by Mesuva** [comment]
Non-physical is the wrong wording to use, just couldn't think of a better term.

Maybe it's just a case of setting a cart limit to 1, or something to mark a product a 'Service product', or 'No quantity option'..  you get what I mean though, for something like a membership product.

**Comment by brucewyne** [comment]
Yeah - how about a checkbox for "Fixed Quantity" and being able to define the quantity?

**Comment by Mesuva** [comment]
I think the main aspect of what I'm trying to describe is that not only would it restrict the quantity to one, but when it was checked it wouldn't show the quantity next to the cart item, or show the quantity change box, or complain if you try and add it again. A subscription or membership doesn't make sense to display a 'quantity: 1' next to it.

**Comment by brucewyne** [comment]
Right. I'm on the same page. I think maybe what wasn't clear about what I said is that defining the fixed quantity would be in the dashboard. I can't think of a reason why you would have a fixed quantity of anything other than 1, but that doesn't mean that someone else wouldn't.
