### ISSUE TITLE
Print Slip

### ISSUE THREAD

**Issue by brucewyne** [VividWeb/vivid_store#119]
Need a basic "Packing Slip" button on order details that is printable.

**Comment by mnakalay** [comment]
sorry for the probably retard question but what data do you think should be on the packing slip?

**Comment by brucewyne** [comment]
Much the same information as seen on the Order Details page minus the order status's probably. 

That said, one issue I've seen come up is pricing information. People will buy a product as a gift and not wish to have the pricing information shown on the slip.
