### ISSUE TITLE
Groups/Categories needs a many-to-many relationship

### ISSUE THREAD

**Issue by brucewyne** [VividWeb/vivid_store#12]
Right now Products are many-to-one with Groups. I think this could use a rethink overall. Making it many-to-many makes sense, but would like to discuss this further regarding potentially tiered groups etc.

**Comment by skybluesofa** [comment]
I haven't looked into the Groups, so I'm not real sure what the requirements are for them, but what about using the 'Topics' attribute? It is a tiered/tree attribute.

**Comment by brucewyne** [comment]
I wouldn't be opposed to them, if we can separate the tree's for objects. i.e. I wouldn't want a tree for product categories available for collections and have to deal with that.

**Comment by brucewyne** [comment]
And I haven't looked into any solution enough to really figure out what's best.

**Comment by Mesuva** [comment]
I have had some thoughts about this, based on something recently where I needed to handle categorising pages under multiple types of category.

In ecommerce products are either categorised by product sets or by their nesting in the sitemap.
I think product sets are great and I think a similar approach should be included in Vivid Store. They're great to do things like 'on sale', 'for kids', etc.

In terms of page nesting however, I never found this particularly great as it would only handle a single categorisation this way (I did override things to be able to utilise aliases, but that's not fun to manage).

What I think would work however, is the ability to associated one or more pages with a product. Then on the Product List block there be the option to 'show products that refer to the current page' (or something along those lines). There could also be a checkbox on the Product List block that says 'show products that refer to any child page of this page'.  Coding wise I think this would be pretty easy to add, but it would be then very flexible as to what you could do with it.  

So I think there should be both Product Sets and Page related categorisation. One or the other, or both options could be used and it would cover a very wise range of scenerios.

I have investigated using 5.7's topics, I've used them already on a production site. Although they're great for certain contexts, I think they'll be too messy to use for product categorisation. If their support was added, I think it would work the same was as pages - you assign a topics attribute to a product and then on a topic list you filter by that topic. So it would work, but I think would be confusing to manage.

**Comment by brucewyne** [comment]
Thanks @Mesuva this is pretty cool now.
