### ISSUE TITLE
Blocks no longer appearing in their own block group in sidebar

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#136]
They're not just appearing under 'Other'.

**Comment by Mesuva** [comment]
Could have been my uninstall and reinstall causing it

**Comment by brucewyne** [comment]
Was this due to a botched install? Block stuff happens after shipping methods... Did the other stuff after shipping get installed?

**Comment by Mesuva** [comment]
It was after a clean install, but I'd been doing a lot of uninstalling and reinstalling.

I'll confirm this on a clean install at some point

**Comment by Mesuva** [comment]
Installed to a fresh install, I can confirm that the blocks aren't appearing in the store grouping anymore
