### ISSUE TITLE
Need labels on Product list in dashboard showing unlimited stock and enabled/disabled status

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#148]
Quick job, just putting this down as a reminder

**Comment by brucewyne** [comment]
From #84 - would it address this: "Product List block should have a new option whether to show products that are in stock or not. Default to no." and if out of stock, show an out of stock label instead of Add to Cart? I haven't seen how much of this is done already... so that could be done.

**Comment by Mesuva** [comment]
I'm really just talking about the Product section in the dashboard where it lists products that have been created. I think on that table it needs some labels to show whether products are actually active or not. 

I agree thought that we'd probably need options on the product list block too.
