### ISSUE TITLE
Guest checkout

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#15]
I think a guest check out is critical to offer.

The checkout could check if any of the products require adding a user to a user group and prevent proceeding until they are logged in. Otherwise I think the shop should support it fine.

(I'm happy to give this feature a shot)

**Comment by brucewyne** [comment]
I don't disagree, but this is probably something less critical to most business compared to many other things. There would be a bit of work involved. Right now taxes is pretty tied directly to the user objects attributes.

**Comment by Mesuva** [comment]
It could be difference in markets, but of the dozen or so ecommerce sites we've set up in the last few years, I'd say we only use registration/logins on two of the sites - all the others all use guest checkouts to keep things as streamlined as possible.

I'll have a bit of look to what might be involved.

**Comment by Mesuva** [comment]
If I get a chance to tackle this, my plan would be to create a Customer class/object that is used to store/fetch customer details, instead of directly using UserInfo objects. 

So instead of directly doing things like $ui->getAttribute("billing_first_name"), it would be more like $customer->getAttribute('billing_first_name'), with the class handling whether it is using a logged in user or whether it is using a session to manage the data temporarily.

**Comment by Mesuva** [comment]
Chuck in development on this one as well, I've made a start on this.

**Comment by brucewyne** [comment]
@Mesuva - You're awesome. Marked as in development

**Comment by brucewyne** [comment]
merged what you had and a couple tweaks I mentioned in. If you can wrap up the tax issues we can close this one :)

**Comment by Mesuva** [comment]
This can be closed
