### ISSUE TITLE
Reinstall products are deleted

### ISSUE THREAD

**Issue by Rgeelen** [VividWeb/vivid_store#154]
When you deinstall the package and reinstall it again the products are deleted. I am not sure if this is intended. But would it not be better that the products and other settings are not removed from the database?

**Comment by brucewyne** [comment]
There's nothing we've changed about the uninstall. So it seems like C5 has changed that. I don't know what is the most acceptable solution and what peoples expectations are for an uninstall. That said, I feel like most people would expect a clean slate after an uninstall. So maybe it's not bad. 

Rerunning the upgrade essentially runs much of the install script anyways.
