### ISSUE TITLE
Stock unlimited / product not in stock.

### ISSUE THREAD

**Issue by Rgeelen** [VividWeb/vivid_store#155]
When marking a products stock as unlimited. The product page and list show that the product is not in stock.

**Comment by Mesuva** [comment]
I think this comes from saving a product initially with unlimited ticked, as opposed to saving it with a quantity first _then_ marking it as unlimited. Will fix asap.

**Comment by Rgeelen** [comment]
The problem for the product detail page is the sellAble check. It only checked if there was a quantity. I added a check to see if the product is unlimited. 

I created a pull request for this a minute ago. 

This only solves the product detail page.

**Comment by Rgeelen** [comment]
In productList.php I added the pQtyUnlim. You can see it in the pull request.

if(!$this->showOutOfStock){
            $query->andWhere("pQty > 0 OR pQtyUnlim = 1");
        }

**Comment by brucewyne** [comment]
I think this needs to be fixed in the isSellable() method instead then.

**Comment by brucewyne** [comment]
Cool - looks like that's what you did in the PR. Thanks!
