### ISSUE TITLE
Add Tax Rate  'taxIncluded' cannot be null

### ISSUE THREAD

**Issue by Rgeelen** [VividWeb/vivid_store#157]
An exception occurred while executing 'INSERT INTO VividStoreTaxRates (taxEnabled, taxLabel, taxRate, taxIncluded, taxBasedOn, taxAddress, taxCountry, taxState, taxCity) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["1", "21", "21", null, "grandtotal", "shipping", "NL", "", ""]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'taxIncluded' cannot be null

**Comment by brucewyne** [comment]
Good catch. Thanks.
