### ISSUE TITLE
Shipping methods are not displayed in the checkout

### ISSUE THREAD

**Issue by Rgeelen** [VividWeb/vivid_store#158]
Error: You must choose a shipping method.

**Comment by brucewyne** [comment]
This is a problem when you have products that you say are shippable but don't define a shipping method. I suppose we can bypass that if we don't have one defined...

**Comment by brucewyne** [comment]
Actually - maybe you can help me figure out what's going on here more. Because on my install, if no shipping method is defined, then it doesn't ask for shipping address or to select a shipping method.

**Comment by Rgeelen** [comment]
The problem occurs when you apply the shipping method to "certain countries". It seems that the multiple select data is not saved. The <select> has no name attribute. When I provide one => name="countriesSelected" an error occurs: implode(): Invalid arguments passed

**Comment by Rgeelen** [comment]
The issue is solved. I have set the select element name to name="countriesSelected[]". Now the values are passed as an array to the controller. You can find the result in the pull request: #165
