### ISSUE TITLE
Product sale price

### ISSUE THREAD

**Issue by Rgeelen** [VividWeb/vivid_store#159]
The sale price is 0 by default. At this moment this results in a 100% discount on the product. 

When setting the prices to the same value (price: 100, sale price, 100) you still see the product as if it is on sale. 

I suggest that when the sale value is 0. The price of the product should only show the product price and when the prices of the sale and the product price are the same. The product should not show as if it is on sale.

**Comment by brucewyne** [comment]
This should have been defaulted to empty. If it's empty there's no sale price. so save it empty rather than 0.
