### ISSUE TITLE
Database table names should be pluralised for consistency with c5 naming convention

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#16]
Although an annoyance, I still think this is worth addressing, as it will assist other developers working on the code.

**Comment by brucewyne** [comment]
I'm very fine with this. I'm going to put the "Help Wanted" label on this. So if you can get to it that'd be awesome otherwise, maybe we can soon.

**Comment by brucewyne** [comment]
@skybluesofa you're playing with this as of right now, correct?

**Comment by skybluesofa** [comment]
That is correct.
