### ISSUE TITLE
Membership system issue

### ISSUE THREAD

**Issue by mnakalay** [VividWeb/vivid_store#163]
Hi again,
When selling a membership product and creating an account upon purchase you have made it so that if the buyer uses an existing email but is not logged in, he's not automatically logged in and a notification is sent. 

I think there are several problems here:
The user is not added to the proper group and the email you are sending states that they can now access the protected content which is not correct.

Shouldn't you either modify the email to warn them of an access or add them to the proper group and send them the existing email?

Frankly the best would be to simply ask them for their password during checkout if the email already exists.

**Comment by brucewyne** [comment]
This question is much for @Mesuva as he worked on a lot of that stuff. So are you saying there's currently no check that the email may already exist as a registered user when checking out for membership stuff? 

If so, then yes - what are your thoughts on doing an ajax search for that email once they've moved to the next field and displaying a nice alert a la twitter?

![twitter](https://cloud.githubusercontent.com/assets/782682/9737017/898aabdc-5612-11e5-859d-56464f40b654.jpg)

**Comment by mnakalay** [comment]
Actually that's not exactky it. There's a check for the email BUT if the email is already in use and the user is not logged in, the user i not added to the proper group AND receives an email saying he now has access to protected content.

Since he wasn't added to the proper group he doesn't actually have the access the email says he has.

An ajax search is a good idea. Maybe a popup login form?

**Comment by brucewyne** [comment]
Well, I'd think that if the e-mail is already in use, then we should not allow them to proceed until they login. wouldn't that solve this?

**Comment by brucewyne** [comment]
that - or enter a different email

**Comment by Mesuva** [comment]
The plan here was that if a user already exists and someone checkouts as a guest, but uses the already used email, the account with that email gets the new user groups and is sent an email that indicates this. At this point there _shouldn't_ be any automatic login. It's only for new accounts that automatic logins would happen, otherwise you could get into other people's accounts by placing transactions.

It sounds like I've just missed something with the allocation of user groups in this case, that would just be a bug I need to address. This code simply wasn't complete on this side of things, so sorry for any confusion here.

I'm not against changing this logic to flag if accounts are already in use, or prompting for login in certain cases, I just found that the logic does work fine for my Snipcart membership add-on, so copying that code in was the easiest thing to do at this point.

**Comment by mnakalay** [comment]
@Mesuva I think the idea is not automatic login. Like you said, that would be an unacczptable security risk.
What could happen is offering to login before proceeding.

On the other hand just allocating the proper group would work as well.

In your logic you first check if a customer is a guest and if he is you check if they are already registered. If they are not already registered you register them and load a new customer object with the proper customer ID.
BUT if they are already registered you only send an email.

So when we get to the part where groups are assigned, the already existing customer is still a guest and doesn't get added to the group.

What needs to happen is you get the user ID since they are already registered and load a new customer object for them as well.

So practically your
    if(!$user)

should end right after login the user and the rest of the code should apply in both situation

**Comment by krebbi** [comment]
I think that's too complicated. 
If the Email already exists as a registered Users email, then the guest has to login or use another email-address. 
exactly like the Twitter-screenshot brucewyne posted already here.

**Comment by brucewyne** [comment]
yes - I think in any case, if there's an email with an account associated with it. They either need to login before continuing, or change the email to proceed.

**Comment by Mesuva** [comment]
From a coding perspective, it's actually easier to just associate the groups with the exiting user, but not log them in, and then send them an email showing they have access (and showing something on screen indicating that they need to log in).  I've got that finished up and ready to submit as a pull request.

However, I'll admit that that approach came out of necessity from the Snipcart Memberships add-on, not out of preference. It does actually work fine in practice, but I can see how it's a little different to what might be expected.

I'll look to see if there is a straightforward way to do some user account checking as part of the checkout process, without having to do too much javascript based look-up-ing.

**Comment by Mesuva** [comment]
This process has been updated with a recent merge, it now throws a warning/error when trying to place an order as a guest, using an email address that has already been used.

Simpler and more inline with the thoughts above.

**Comment by brucewyne** [comment]
I think think this is now addressed? Let me know otherwise.
