### ISSUE TITLE
Individual order items need to record tax amount/rate

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#17]
When an order is recorded, it may include items that are both taxed and not taxed.
Therefore the VividStoreOrderItem table needs to include details of what tax the individual line item included. It should store:
- The name of the tax rate applied
- Either the amount of tax applied to that item, or the percentage used at the time of transaction
- Whether the tax was already part of the item price or not 

This is important for creating detailed order invoices and for reporting.

**Comment by brucewyne** [comment]
I certainly like it just from the reporting aspect alone. I know many other systems actually don't record it as a line item, but that's also somewhat a frustrating thing.
