### ISSUE TITLE
Translations need updating

### ISSUE THREAD

**Issue by brucewyne** [VividWeb/vivid_store#178]
I'm tagging anyone who's been apart of helping with translations. 3.0 has a lot of new features and quite a bit of new verbiage. If you could help, it would be appreciated.

@Remo
@LeenDa
@companyou
@tao-s

**Comment by Remo** [comment]
I started to add some more German translations https://github.com/VividWeb/vivid_store/pull/179

**Comment by julehti** [comment]
I have finished v. 3.0  translation in Finnish. Another person has made kindly a previous non-public translation and I translated the new strings and checked the whole translation.

**Comment by brucewyne** [comment]
To those following this, 3.1 will be in the MP next week. Everything in the repo is complete as far as the front end goes. So if you see anything left, help us out. :)
