### ISSUE TITLE
Orders display errors if shipping method referenced is deleted

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#183]
If an order is placed and then a shipping method is deleted, an error is thrown when the order is viewed in the dashboard.

The shipping method and payment method name should be copied and stored against the order, instead of the ID.

<img width="1265" alt="screen shot 2015-09-13 at 8 19 58 pm" src="https://cloud.githubusercontent.com/assets/1079600/9836341/e3b63554-5a54-11e5-9aae-8c600071dbaa.png">

**Comment by brucewyne** [comment]
Agreed. I imagine the same goes for payment method as well. Not sure, but likely

**Comment by Mesuva** [comment]
It probably does, the same copying should apply to those as well.
