### ISSUE TITLE
Feature enhancement - would prefer if the discount code could be entered directly at checkout screen

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#184]
As a quick solution I made the 'Enter Discount Code' link to the cart, to add the discount code there.
I've seen on other shopping carts where such a link unhides an entry box underneath. 

It could still be a basic submit form, where it does a full refresh of the page, but I think it would be tidier.

Something to flag for 3.1

**Comment by brucewyne** [comment]
Yes - though I'd still prefer that it be a click-to-add sort of thing. Clicking the link could simply display the field.

**Comment by brucewyne** [comment]
Closing. Discounts is becoming legacy.
