### ISSUE TITLE
Wrong Price in Order View

### ISSUE THREAD

**Issue by krebbi** [VividWeb/vivid_store#185]
Using a sales price is not shown in the Order View.
Normal price for the product is 600,- and sales price is 550,- . shipping is 7,-
Price and Subtotal is wrong. See Screenshot. 

![bildschirmfoto 2015-09-15 um 00 33 42](https://cloud.githubusercontent.com/assets/3884521/9863574/7ae46e18-5b41-11e5-863f-3b84435efbe7.png)

**Comment by brucewyne** [comment]
Is this using the latest version from git?

**Comment by krebbi** [comment]
yes. just pulled and reinstalled the package.

**Comment by krebbi** [comment]
Adding that "on sale" product to the cart and having an active discount makes it just more strange. 
I think here is some more explanation necessary for the end customer. ;)

![bildschirmfoto 2015-09-15 um 00 41 40](https://cloud.githubusercontent.com/assets/3884521/9863723/bed24888-5b42-11e5-886b-a02554160efb.png)

**Comment by brucewyne** [comment]
yup - both of those were bugs. Thanks for reporting! Just fixed them here. It won't fix the order details because it got saved that way, but will fix new orders and the cart

**Comment by krebbi** [comment]
last but not least the discount calculation is a bit strange.. 
as you can see in the screenshot I created a "Big Summer Sale" Discount with 10% and the "Special Discount" with the Code "DEEZNUTS". ;) 
Whatsoever the "Summer Sale" is also triggered by "DEEZNUTS" and the Grand Total is complete over the top but the Item price is not discounted at all. 

![bildschirmfoto 2015-09-15 um 00 47 53](https://cloud.githubusercontent.com/assets/3884521/9863843/01a69352-5b44-11e5-8c13-2126f3df2128.png)

**Comment by brucewyne** [comment]
Not sure I follow - just the item amounts were wrong, yes?

**Comment by brucewyne** [comment]
that said - pull it down again and try again and let me know if there's still an issue

**Comment by krebbi** [comment]
still an issue. 
Item Subtotal is wrong with 2 discounts. should be -10% and on that value -5%. so it's not 15% in total. ;) 
both discounts beside the "on sale" price are missing. 
The total is 47.032,00 but it should be 470,25 + 7,- shipping = 477,25

![bildschirmfoto 2015-09-15 um 00 57 22](https://cloud.githubusercontent.com/assets/3884521/9863969/2a7dd0e6-5b45-11e5-8943-f307c728b302.png)

**Comment by krebbi** [comment]
should I open an new Issue for this one?

**Comment by brucewyne** [comment]
Yes - and tag Mesuva
