### ISSUE TITLE
Shipping Price

### ISSUE THREAD

**Issue by krebbi** [VividWeb/vivid_store#186]
Here in Germany we have a basic package size which is insured for € 6,90
Unfortunately the shipping method only saves integer values for the prices.

**Comment by brucewyne** [comment]
can you not enter it in as 6.90 and save it and it work fine?

**Comment by krebbi** [comment]
no: http://krebernik-it.com/files/3914/4234/5223/shipping-price.mov

**Comment by brucewyne** [comment]
Oh oh! I see

**Comment by krebbi** [comment]
and could you check the input for "," also? that's the usual separator here in europe (except UK, but that's another story..)

**Comment by brucewyne** [comment]
fixed. prices should be entered as a standard with decimals. It's less about the currency format. That's what the currency formatting is for
