### ISSUE TITLE
Multiple issues with discounts

### ISSUE THREAD

**Issue by brucewyne** [VividWeb/vivid_store#189]
Don't know how to recreate all of these
1. Can't use more than one discount code even if both aren't exclusive
2. Subtotal always needs to accurately be just the subtotal.
   2b. Discount should add a new line item to show the discount amount
3. Price in Order detail is drastically wrong compared to cart totals

**Comment by krebbi** [comment]
i hope that helps reproducing: 

create a product and add a nice "on sale" price.
create an active discount, let's say "summer sale" with 10%.
create a discount with code. 

now shop that product and use the discount code. 

issues:
Grand Total is totally wrong
"Discounts Applied" Items Subtotal is wrong and Total is completely wrong.
"Triggered" Is wrong for the normal active Discount, which is not triggered by any code.

see https://github.com/VividWeb/vivid_store/issues/190

**Comment by krebbi** [comment]
and may i add: 
the display of the discounts should be improved for the cart / add to cart as a ordinary mortals really don't get it with all those figures. :)

**Comment by brucewyne** [comment]
agreed

**Comment by brucewyne** [comment]
may I ask how you're entering your prices in the products/shipping/tax and all that? With commas?
Do you know how it stores it in the database?

We have a Price::getFloat() method we may want to run on all user inputs regarding prices, which converts numbers down to a normal float.

**Comment by krebbi** [comment]
i have no tax active and the product prices are without decimal places.
what data do you need from the DB? 
the only comma I want to have is the shipping 6,90 which is another issue.

**Comment by brucewyne** [comment]
with shipping, you shouldn't even be able to enter 6,90. Though you should be able to enter 6.90.

**Comment by krebbi** [comment]
that's true, but it doesn't change the fact that it stores 7.

**Comment by brucewyne** [comment]
@krebbi that's in regards to #186 and has been fixed and closed. (pull down the latest version and run the upgrade script)

**Comment by mkly** [comment]
FYI php is pretty fun with commas and numbers

https://3v4l.org/ircEE

I wonder if this has anything to do with the strangeness.

**Comment by krebbi** [comment]
sorry, my bad: the shipping 6.90 is fixed. 
had to reinstall the package to get that working

**Comment by brucewyne** [comment]
@mkly - I think commas are limited to the presentation. We use Price::format($price) to add in commas. It should all be floats otherwise. 

@krebbi - it looks like you're using a period as a thousands separator. Is that normal in parts of europe?

**Comment by krebbi** [comment]
yes, that's the official way to do it: normal numbers need to have a space as thousands separator but money uses a "." It's written in DIN 1333.  
But there is another standard in ISO 80000 where everything else than a "small space" is forbidden as thousands separator. whatever a "small space" is...

**Comment by brucewyne** [comment]
Could you tell me what the oTotal column is for a most recent order in the VividStoreOrders table?

**Comment by krebbi** [comment]
![bildschirmfoto 2015-09-16 um 00 28 01](https://cloud.githubusercontent.com/assets/3884521/9891849/d065e8e4-5c09-11e5-8d25-304edb1bb987.png)

**Comment by brucewyne** [comment]
Much of the pricing stuff has been fixed.
