### ISSUE TITLE
Discount codes

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#19]
A feature for the long term!

**Comment by brucewyne** [comment]
Yeah - this is a big ticket item. I don't think we would be able to get to it until later (early/mid next month). So I'm putting Help Wanted on here, because this is kind of a huge need.

**Comment by Mesuva** [comment]
I've been thinking about some of the code types would be handy:
- Price/Percentage off of total
- Price/Percentage off shipping (free shipping if 100%)
- Percentage/price off a particular product (or products)
- Maybe a percentage/price off of any product in a particular product group

For each code:
- When it is applied (when entered, when order > amount, for a user group, etc)
- Maximum number of uses
- Making it available only to one or more user groups
- Expiry date

It could start of with just the basics, but I thought it would be handy to mention these things for future thinking. Snipcart has a surprisingly sophisticated set of options for discount code and I think is worth using for inspiration.

I'm tempted to work on the backend stuff myself first, to provide a dashboard panel to allow them to be managed and configured. Then the actual processing and entry of codes in the checkout could be handled as a separate dev activity.

**Comment by brucewyne** [comment]
Yeah - having been drowning in Magento, and working with their discount codes etc, I've got a lot of inspiration there as well.

I think this is a good list to jump start on.

For more complex examples there's ideas like:
- If X amount of products are added
- if shopping cart total is minimum of X

**Comment by Mesuva** [comment]
My other thought with discount codes is that I think the way they stored needs to be split it to 'discount rule' and 'code', so two separate tables.

This means that you then could set up a rule that has single use codes, but you wouldn't have to configure the rule every time you wanted a new code. You could also set up the rule, then perhaps do a cut and paste of a big long list of codes for them to be created against that rule.

**Comment by Remo** [comment]
In our system we've had coupon codes which were something like gift card. Use them once and they are gone. To create them, we've had this screen:
![image](https://cloud.githubusercontent.com/assets/129864/8006919/361d12d8-0b98-11e5-8170-6d3f2a88a9fb.png)

We've also had promtion codes which were usable by many users. They were something restricted to product groups (you don't get a discount for alcoholic beverages and things like that)
![image](https://cloud.githubusercontent.com/assets/129864/8006938/67808184-0b98-11e5-8a09-511048e6208f.png)

**Comment by erik-maas** [comment]
Mesuva, that is a good idea for power users. But i know that many c5 users choose it for it's ease of use. I think it would be easier to just have a single discount code page where you can add the rule and the code. It's easier as you don't have to learn the abstract concept of decoupled rule/code.

However, it could be possible to store a preference rule, and use it. This makes both workflows possible.

**Comment by Mesuva** [comment]
I've made a little start on this, perhaps mark it as in development
