### ISSUE TITLE
Discount Prices - wrong calculation

### ISSUE THREAD

**Issue by krebbi** [VividWeb/vivid_store#190]
Item Subtotal is wrong with 2 discounts. should be -10% and on that value -5%. so it's not 15% in total. ;)
both discounts beside the "on sale" price are missing. 
The total is 47.032,00 but it should be 470,25 + 7,- shipping = 477,25

![2a7dd0e6-5b45-11e5-8943-f307c728b302](https://cloud.githubusercontent.com/assets/3884521/9890668/9c144d68-5c01-11e5-822f-6e8d1ffe87b5.png)

**Comment by brucewyne** [comment]
I'd like for you to check again and see how much of this is resolved
