### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by brucewyne** [VividWeb/vivid_store#192]
With a lot of features developed now, I'd like to take some time to do some major code cleanup.

Some things I'd like to consider:
- Replacing all legacy ADODB methods. Part of me wants to consider moving everything into ORM. This does two things which are good and bad. 1. With this add-on being looked at by a of people, it sets a high standard to learn from. 2. It also requires learning a new skillset which may reduce the amount in which people can easily contribute.
- Many Classes (namely Products, Orders, Cart) do too much work. These likely need to be broken down more.

**Comment by krebbi** [comment]
Concrete\Package\VividStore\Controller\SinglePage\Dashboard\Store\Products in function add() (line 76) should be 

$gl = new GroupList();

sorry, too lazy for a pr.
