### ISSUE TITLE
Could use some basic reporting

### ISSUE THREAD

**Issue by brucewyne** [VividWeb/vivid_store#2]
Need a new dashboard page for some basic reporting:
- Sales totals
- Best sellers
- Products Sold
- Total Tax
- Total Shipping

all should be filterable by date range

**Comment by skybluesofa** [comment]
I'm going to start on this.

**Comment by brucewyne** [comment]
Hey-o @skybluesofa  - any update on this?

**Comment by brucewyne** [comment]
@skybluesofa haven't heard from ya so we'll start tackling this ourselves.

**Comment by brucewyne** [comment]
Done.
