### ISSUE TITLE
when using external payments, email notification is sent too early

### ISSUE THREAD

**Issue by brucewyne** [VividWeb/vivid_store#210]
There's a check whether or not the payment method is external. However, it's looking in the wrong place.

**Comment by Mesuva** [comment]
Is this still the case?  Should I just try to test some paypal transactions?

**Comment by brucewyne** [comment]
in general, it was a little odd. the paypal controller itself wasn't a big deal as much as things we split between add and complete order. Here that's been completely refactored.
