### ISSUE TITLE
Quantity can be changed to a decimal

### ISSUE THREAD

**Issue by brucewyne** [VividWeb/vivid_store#220]
When editing the cart - you can change the qty to a decimal. This also causes errors

**Comment by Mesuva** [comment]
I wonder if this could actually be a 'feature' if it was fixed to work and be an option.
I've seen some online shops sell stuff by the kilo, where you could type in a decimal.

e.g. http://shop.beerbelly.com.au/barrett-burston-ale-5-ebc.html

Just a thought!

**Comment by brucewyne** [comment]
If so, then it's an option that HAS to be set at the product level. The same store that's selling grains and t-shirts will not want to sell 1.65 of a t-shirt.
