### ISSUE TITLE
Package getConfig deprecated?

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#23]
I could be wrong about this, but I was under the impression that storing configuration settings via $pkg->getConfig() is now considered legacy, with the Config class now being the preferred approach.

As Config uses flat files to store data it's faster too.

**Comment by brucewyne** [comment]
I think you're thinking of $pkg->saveConfig() etc...

$pkg->getConfig() is not deprecated.

**Comment by Mesuva** [comment]
Well deprecated isn't the right word, it's still available. I just thought the suggestion now was to use the non database way of storing config data.

**Comment by brucewyne** [comment]
There's likely a few things like that, that are not the v7 best practices. Likely a lot of stuff from the early days of putting this together for the first client (November). So I'm open to cleanup, suggestions, and better best practices.
