### ISSUE TITLE
Memberships & Downloads - timelimit? 

### ISSUE THREAD

**Issue by krebbi** [VividWeb/vivid_store#231]
Do you guys think it's possible to limit the usergroup assignment to a certain duration like 48h or 1year?

**Comment by Mesuva** [comment]
That should be possible straight away - there are time limits options on user groups built in concrete5, just edit a user group in the dashboard and you should see the options there.

**Comment by krebbi** [comment]
wo-hoo, that's great! 
why are the best features of 5.7 so hidden..?! 
nevertheless, my "issue" is solved.
