### ISSUE TITLE
Adding a product

### ISSUE THREAD

**Issue by krebbi** [VividWeb/vivid_store#235]
adding a product results in this error:

An exception occurred while executing 'INSERT INTO VividStoreProducts (cID, pName, pDesc, pDetail, pPrice, pSalePrice, pFeatured, pQty, pQtyUnlim, pNoQty, pTaxClass, pTaxable, pfID, pActive, pDateAdded, pShippable, pWidth, pHeight, pLength, pWeight, pCreateUserAccount, pAutoCheckout, pExclusive) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "8\" 2208 3-4S 400mm", "", "", "600", null, "0", "999", null, "0", "1", "0", "0", "1", "2015-10-15 10:24:02", "1", "0", "0", "0", "0", 0, 0, false]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'pQtyUnlim' cannot be null

**Comment by brucewyne** [comment]
thanks for catching that. There's a few I noticed I need to set to nullable.
