### ISSUE TITLE
Price field doesn't have enough room when prefix added

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#240]
![screen shot 2015-10-19 at 5 12 31 pm](https://cloud.githubusercontent.com/assets/1079600/10571225/a42e2170-7684-11e5-9c2d-9577e799e12e.png)

**Comment by brucewyne** [comment]
I think there's likely a different/better way to address this, which would be in the Currency section of settings. There we should select which currency we're using, and an option for how we should display it (e.g. Not at all, prefix/affix to symbol, affix to end...) and let our Price::format() method add it in appropriately.

This would have several down the road benefits. For example, if we have multiple currencies, we can use this configuration to pass which currency we're using to the payment processor. As well as limit what payment options to show depending on the currency etc.

**Comment by Mesuva** [comment]
This has been fixed for now at least
