### ISSUE TITLE
SKU# and pricing

### ISSUE THREAD

**Issue by pvernaglia** [VividWeb/vivid_store#242]
Hi Guys, The store is really shaping up from the first time I looked at it, good work! 

I think you really need to add SKU# for all products, it's pretty standard and I think it will be needed for inventory control.

On Options, would be nice to have the ability to give a prices for different options.  Small, Medium, Large might want to be three different prices or additional charge (with different SKU#'s).  Some stores do this by entering three items then being able to relate them to one an other.   I think it something people will be asking for.

Thanks

**Comment by brucewyne** [comment]
Agreed. This is something brought up in #80 and #31 

It hasn't happened yet because breaking out options into a matrix to customize the inventory/price/sku is pretty complicated. It's easy to just add a sku to the product, but that's just the beginning of what it actually entails

**Comment by krebbi** [comment]
that could be done by creating a product attribute, couldn't it?

**Comment by Mesuva** [comment]
This will be worked on soon

**Comment by typoman76** [comment]
This would be a great step forward!

**Comment by brucewyne** [comment]
this is done and closed.
