### ISSUE TITLE
Checkout -> Complete Order

### ISSUE THREAD

**Issue by krebbi** [VividWeb/vivid_store#249]
An exception occurred while executing 'INSERT INTO VividStoreOrders (cID, oDate, pmName, smName, oShippingTotal, oTax, oTaxIncluded, oTaxName, oTotal, transactionReference) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["1", "2015-10-27 14:48:52", "Invoice", null, 0, null, "", "", 380, null]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'smName' cannot be null

**Comment by Mesuva** [comment]
Fixed in #252
