### ISSUE TITLE
Configure/restrict country lists for billing and shipping addresses

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#25]
I think we need some config settings for these fields.

**Comment by brucewyne** [comment]
@Mesuva  Probably less so for the billing, and more so for the shipping, yeah? As I'm working on shipping methods I've thought of limiting the available shipping countries to whatever there's a shipping method for.

e.g. if you only have shipping methods for australia, then you only have australia as an option. If you have a flat rate for australia, and calculated postage for the rest of the world via UPS or the like, then all countries are listed.

Thoughts

**Comment by brucewyne** [comment]
Or at the very least, always show the countries list, but if there's no shipping methods, when you reach the shipping method pane, you get a friendly "Sorry, but we don't offer shipping to that country. Contact us for further assistance". Additionally, you would not be able to proceed.

**Comment by Mesuva** [comment]
Well maybe more-so for the shipping, but it would still be important to restrict the billing address, I've done that on a few sites.

I get what you are suggesting with tying it directly to the shipping methods, but I think that might be get kind of tricky to configure for some setups.. I might want to use Fedex here in Australia, but not actually offer shipping overseas for example. (or maybe you're suggesting that each method when configured would have a list of countries you pick?)

So I still think it would be better to just have some sort of select list to restrict the two drop downs initially. I actually like the idea of 'please contact for ordering', rather than not having someone's country in a list - it suggests that you didn't just exclude them entirely.

**Comment by brucewyne** [comment]
Right - so for each method you add you would have the option of "All Countries or Some Countries", if some countries you get a multiselect of countries for that method.

So you could set up FedEx for Australia only, and postal for some other limited amount of countries. Something like that. 

Billing I feel you should never limit. I've encountered a lot of random countries ordering gifts for their grandsons etc living in a country you do cater to.

**Comment by Mesuva** [comment]
I've had cases where billing needed to be restricted - professional memberships being one of them, where it was restricted to those in the US.

**Comment by brucewyne** [comment]
makes sense, and to your benefit, I should also have to say that ideally nothing is set in stone. Everything _should_ be optional/configurable.

**Comment by Mesuva** [comment]
I might look at this next. I'll just do a basic filter of the two country lists based on a setting in the dashboard.

**Comment by brucewyne** [comment]
let me know if/when you do.
