### ISSUE TITLE
Checkout - Grand total Discount wrong calculation

### ISSUE THREAD

**Issue by krebbi** [VividWeb/vivid_store#250]
See Screenshot

![bildschirmfoto 2015-10-27 um 14 48 38](https://cloud.githubusercontent.com/assets/3884521/10759869/29671582-7cba-11e5-8fdc-1f0bfc8a7be2.png)

**Comment by Mesuva** [comment]
That looks like the discounts have been somehow skipped in the more recent changes to the cart code. 
I'll try to look at this soon.  

(I'm personally not using discounts on projects yet, that feature was very loosely put together)

**Comment by krebbi** [comment]
Me neither, just testing it anyway. :)

**Comment by krebbi** [comment]
may I add to this context, that the discount is now displayed nowhere in the order view (/dashboard/store/orders/order/1), just the grand total is decreased accordingly:

![bildschirmfoto 2015-11-02 um 18 04 39](https://cloud.githubusercontent.com/assets/3884521/10888425/67749ec2-818c-11e5-84db-4019a7a23c9d.png)

this could lead to some irritations. :)

**Comment by Mesuva** [comment]
This is weird, I was sure we had some mention of discounts on this screen, perhaps it's just not being passed through to display anymore.

**Comment by krebbi** [comment]
just seen that the previous point is already an issue/enhancement: https://github.com/VividWeb/vivid_store/issues/206

**Comment by brucewyne** [comment]
Closing legacy Discount system tickets.
