### ISSUE TITLE
Payment Gateway

### ISSUE THREAD

**Issue by pvernaglia** [VividWeb/vivid_store#256]
HI, Is there anyone who would be able to assist with a payment getaway for DPS?  They are a big service in New Zealand.  A gateway does exist for 5.6x Core Commerce.  If anyone would be able to work on this for us please contact me at peter@webli.us

**Comment by Mesuva** [comment]
Are they otherwise known as Payment Express?

I've got an Omnipay based payment method working in production (with a couple of gateways), and since Payment Express appears to be supported via Omnipay it hopefully would be be a pretty straightforward gateway to add in.

I'll drop you an email.

**Comment by brucewyne** [comment]
@Mesuva @pvernaglia https://www.concrete5.org/marketplace/addons/dps-payment-express/ - the 5.6 one he mentions seems to be PaymentExpress as well.

Store includes OmniPay Core. This allows anyone to develop a payment gateway fairly easily. @Mesuva has done one with it, so he'd probably be a good choice to do another. I think the most complicated part would be being familiar with the gateway and getting a test account to make sure everything works well.

**Comment by pvernaglia** [comment]
Yes it is DPS Payment Express.  I have a client in New Zealand who has a lot of experience with it and the test accounts.

**Comment by Mesuva** [comment]
As an issue, this can be closed
