### ISSUE TITLE
Product List Features

### ISSUE THREAD

**Issue by brucewyne** [VividWeb/vivid_store#26]
At some point next week we'll be dealing with a couple extra sort options for the product list (like adding "Most Popular")

Any other sort or filter options we should consider while we're in this area?

**Comment by Mesuva** [comment]
On the product block I'd love to have a checkbox to exclude the product currently on the page (so an extra filter).

**Comment by brucewyne** [comment]
Would it be more flexible to add an active class to that product? That would give you the easy option of either hiding it via css, or highlighting but disabling it.

**Comment by Mesuva** [comment]
Good point, I think that would be more flexible than just removing it. Good one!

**Comment by mnakalay** [comment]
It would be good to be able to show most popular products in general AND per category as well as to be able to "select" which should be most popular.

I assume "most popular" should be based on sales but how about if I want to push a particular product?

**Comment by brucewyne** [comment]
@mnakalay Thanks for chiming in. There currently is a featured attribute in the product list and in product management. So that's cuts the list to just promoted products. Then you could further use the sort by to get it how you want (most popular, alpha, newest etc).

Can you see another way you would use it?
