### ISSUE TITLE
Uncaught Query Function on Product Edit Page

### ISSUE THREAD

**Issue by Blenderite** [VividWeb/vivid_store#260]
Not sure if this is relevant at all, but I thought I would post it here so at least yall are aware.

I get this error when I Ctrl + Shift + I: Uncaught query function not defined for Select2 s2id_autogen1

![capture](https://cloud.githubusercontent.com/assets/6311229/10968905/b16c7ccc-8392-11e5-984f-014fdb7996c9.PNG)

**Comment by Mesuva** [comment]
I'm not able to replicate this.
