### ISSUE TITLE
Placing Order Causes Exception

### ISSUE THREAD

**Issue by justrjlewis** [VividWeb/vivid_store#271]
Vivid Store install has an exception when someone places an order.  Here's the exception: 

```
An exception occurred while executing 'SELECT count(distinct p.pID) FROM VividStoreProducts p INNER JOIN VividStoreProductLocations l ON p.pID = l.pID and l.cID in (240) WHERE (pFeatured = 1) AND (pQty > 0 OR pQtyUnlim = 1) AND (pActive = 1) GROUP BY p.pID ORDER BY pID = ? DESC LIMIT 1' with params ["17"]: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'pID' in order clause is ambiguous
```

environment settings: https://www.concrete5.org/marketplace/addons/store-ecommerce-from-vivid/support/product-order-causes-error-to-display/

**Comment by Mesuva** [comment]
I'm pretty sure this is a duplication of issue #276 - as that has a bit more detail as to the problem I'm going to close this particular one, thanks @justrjlewis .
