### ISSUE TITLE
Feature: ability to disable adding to cart/ordering with dashboard switch

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#274]
This is something I'm wanting to add to the shop soon, I had two requests for such a feature over xmas/new years.

Basically I'd love a feature where you can just globally turn the shop off, potentially with a message in place of the cart button.

**Comment by Mesuva** [comment]
I might update this to suggest it would be worth making this a bit more than just on/off, as it could potentially be used to enable 'catalogue' mode.
- Adding to cart and ordering enabled
- Ordering disabled
- Catalogue mode

**Comment by brucewyne** [comment]
This is not a feature I see worth persuing. All blocks allow you to turn off the add to cart link. You can already essentially do this.
