### ISSUE TITLE
Wrong update quantity product

### ISSUE THREAD

**Issue by nasir88** [VividWeb/vivid_store#275]
See screenshot

![quantity update issue](https://cloud.githubusercontent.com/assets/6658513/12377727/44bc834c-bd62-11e5-8d47-e0af1d4eaa69.PNG)

**Comment by Mesuva** [comment]
A fair bit of the cart adding code is currently being re-worked, so this will hopefully be addressed (I couldn't replicate, but I have no doubt there's some bugs in the current add to cart code)

**Comment by Mesuva** [comment]
I believe this has been fixed in #279

**Comment by brucewyne** [comment]
Closing. I assume this is resolved, but also can't recreate.
