### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by pvernaglia** [VividWeb/vivid_store#276]
HI, I have a site in development with Store, it was all working fine last night, but this morning when I tery to go to the site I am getting an error:

 Doctrine \ DBAL \ Exception \ NonUniqueFieldNameException

An exception occurred while executing 'SELECT count(distinct p.pID) FROM VividStoreProducts p INNER JOIN VividStoreProductLocations l ON p.pID = l.pID and l.cID in (171) WHERE (pQty > 0 OR pQtyUnlim = 1) AND (pActive = 1) GROUP BY p.pID ORDER BY pID = ? DESC, pID = ? DESC, pID = ? DESC LIMIT 1' with params ["2", "3", "4"]: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'pID' in order clause is ambiguous 

The client was on the site after me checking things and may have tried to do a test purchase, but I'm not sure exactly what she may have done.  Anyone have some thoughts on this problem?

thanks

**Comment by Mesuva** [comment]
I think this is to do with product lists when they are ordered by 'Most Popular' (not something I've used myself at this point).

If I try to use that feature, I get a bunch of errors to do with looking up existing orders, so I'm not sure how reliable that feature is at this point. 

My suggestion would be to look for where you have product list blocks and set them to a different sort order - that's my guess as to what I think your client may have changed.

**Comment by pvernaglia** [comment]
It does seem to only be crashing the two pages that have the product list block on them, I don't think they would have gone in and made any changes, they were just looking the site over for approval and setting up their paypal info

**Comment by Mesuva** [comment]
From the error message, the bit that it's complaining about is pID in the order clause, which from what I can see only gets added to the query in line 115 of VividStore\Src\VividStore\Product\ProductList, which looks to be part of the popular sort functionality.

**Comment by pvernaglia** [comment]
You were right, the problem did not show up until some sales were placed, I changed the sort order in the db and the error went away
