### ISSUE TITLE
Product List Block Errors

### ISSUE THREAD

**Issue by pvernaglia** [VividWeb/vivid_store#277]
Selecting "Most Popular" causes db errors.

I made some changes to add sort by price highest/lowest for a project I am working on, but sorting does not work properly because the pPrice column in the DB is defined as type varchar, changing it to decimal makes sorting by price works properly.  I would propose changing the db type on price columns, I think sorting the product list by price is a good feature.

**Comment by Mesuva** [comment]
I'm pretty sure pPrice on Products is actually defined as a decimal, at least in github (perhaps on the marketplace version it is not).
