### ISSUE TITLE
Installing Git Files

### ISSUE THREAD

**Issue by pvernaglia** [VividWeb/vivid_store#278]
Hi, I'm running the version I downloaded from C5, but would like to get the current files here on Git set up to work with.   I get errors if I try to install the files downloaded from git.  is there something special I need to do?  Something with Composer?  Thanks

**Comment by Mesuva** [comment]
What kind of errors do you get?
I just downloaded a copy directly from git (specifically a branch I've done a PR for) and installed it to a fresh c5 install. Although Composer is used to pull in libraries, these have been included in github, so there's no need to use it to get it installed.

**Comment by pvernaglia** [comment]
I just did a clean install of 5.7.5.5, used the vivid store files from the master here, on installation I get this message now:

Class 'Concrete\Package\VividStore\Src\VividStore\Payment\Methods\AuthNet\AuthNetPaymentMethod' not found 

I do see the file on the server

**Comment by pvernaglia** [comment]
If I uninstall it after it crashed the first time, then try to install it again I get:

Interface 'DVDoug\BoxPacker\Box' not found

**Comment by Mesuva** [comment]
What kind platform and PHP version are you running?

**Comment by pvernaglia** [comment]
php 5.53 on CentOS 6.5 x64 VPS

**Comment by ArniPL** [comment]
I also have problem with `Interface 'DVDoug\BoxPacker\Box' not found`. Do you have a solution to this? Thanks.

**Comment by brucewyne** [comment]
Quite of few of these issues have been resolved.

**Comment by dbleisch** [comment]
i get the same errors with version 3.1.1 on concrete 5.7.8, centos 7.2, php 5.6.12 and apache 2.2.
any suggestions, where to focus on? 

```
Whoops \ Exception \ ErrorException (E_ERROR) 
Interface 'DVDoug\BoxPacker\Item' not found
/webroot/htdocs/packages/vivid_store/src/VividStore/Shipping/Clerk/ClerkItem.php
<?php 
namespace Concrete\Package\VividStore\Src\VividStore\Shipping\Clerk;

class ClerkItem implements \DVDoug\BoxPacker\Item
{
    public function __construct($aDescription, $aWidth, $aLength, $aDepth, $aWeight)
    {
        $this->description = $aDescription;
        $this->width = $aWidth;
        $this->length = $aLength;
```

**Comment by brucewyne** [comment]
If you're installing from git, you now need to run composer.

**Comment by brucewyne** [comment]
from the MP you should be fine. Let me know if otherwise.
