### ISSUE TITLE
php7 compatibility

### ISSUE THREAD

**Issue by krebbi** [VividWeb/vivid_store#286]
have you guys already addressed php7 support?
atm i get

Declaration of Concrete\Package\VividStore\Block\VividProductList\Controller::registerViewAssets() should be compatible with Concrete\Core\Block\BlockController::registerViewAssets($outputContent = '')

when trying to run the store on a php7 environment. 

cheers

p.s. when do you merge the current open PRs?

**Comment by Mesuva** [comment]
I've had this on my todo list!
Here's the PR: #287
