### ISSUE TITLE
Optimisation on select box 'In product groups' 

### ISSUE THREAD

**Issue by difi68** [VividWeb/vivid_store#290]
A little suggestion according the look and feel of the select box 'In product groups'.

set up a placeholder in case there are no groups/categories added or not choosen from a given list.

Proposal : 
Change line in _/packages/vivid_store/single_pages/dashboard/store/products.php_
`<select multiple="multiple" name="pProductGroups[]" class="existing-select2 select2-select" style="width: 100%" <?php  echo (empty($productgroups) ? 'placeholder="no categorie available"' : 'placeholder="select categorie"'); ?>>
`

**Comment by brucewyne** [comment]
We already have a "no results" once you click it. I feel like that's currently strong enough.
