### ISSUE TITLE
Add Filter option could be really great

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [VividWeb/vivid_store#291]
1) **Filter By** - This is something that any store could have . Its Really Really important (The link i added - 3905 Sales on codecanyon)

Like this (not have to be with AJAX):
http://mihajlovicnenad.com/demo/?item=WooCommerce_Product_Filter

2) ***_"Add product options"_-** "SAVE SET" - For example if i have 1,00 T-Shirts  - all off them with the same "OPTIONS" : "XS-S - M - L - XL - XXL" . 

It would be great if you can "SAVE SET"--> "T-shirt-sizes" and than reuse this on product or apply to entire category (In most situation you need the same options on a lot of products).  

I dont know how to add "Pull Requests" so i wrote this her. Thanks :)

**Comment by brucewyne** [comment]
Slow reply -sorry. The first idea is a great idea for a premium add-on. It's a HUGE project in itself. I've actually built this for other custom systems. I can't see it as part of the core here.

The second idea is great though. Almost like a "favorites". I opened a new ticket based on this idea: #297

**Comment by brucewyne** [comment]
Closing this since it's multiple topics to carry.
