### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by krebbi** [VividWeb/vivid_store#292]
Hi guys.

is there a roadmap on what you are working or on which parts you need assistance? 
or is this promissing store a dead end now?

**Comment by typoman76** [comment]
I'm interested in this too. There are some great pull-requests from mesuva waiting to be merched. But I'm unsure if this project will move further? 
The official package on concrete5 still has bugs and is not ready for production in my eyes - but really near that.

**Comment by brucewyne** [comment]
I had given mesuva access to merge those requests, so I'm not sure why they aren't merged already by him. This is not a dead development, but it had been on a hiatus on my end for a couple months and should be picking up more speed and features over the next couple of months.

**Comment by Mesuva** [comment]
@brucewyne - you'd given me access to tag and close issues, I'd specifically said that I wasn't going to do merges. I think there's been a misunderstanding here.

**Comment by krebbi** [comment]
so this seems to be dead anyways... a pity..

**Comment by brucewyne** [comment]
Not really. I had moved away to do some other things (like plan a wedding). I definitely did misunderstand that Mesuva would help by merging in some things. In either case, this project is far from dead. I just had to take a nap.

**Comment by brucewyne** [comment]
FWIW - there's been an immediate roadmap here: https://github.com/VividWeb/vivid_store/wiki/Roadmap

This project is a couple days away from the first release in months (as well to the marketplace). It's currently pending some testing and additional finishes on a brand new promotions/discounts tool.
