### ISSUE TITLE
Creating user after purchasing digital product

### ISSUE THREAD

**Issue by edbeeny** [VividWeb/vivid_store#293]
I'm am getting this error during the check out process.

Argument 1 passed to Concrete\Core\Permission\Access\Entity\UserEntity::getOrCreate() must be an instance of Concrete\Core\Support\Facade\UserInfoFactory, null given, called in /home/packages/vivid_store/src/VividStore/Orders/OrderItem.php on line 58 and defined

Can't see what is causing this. Running C5 version 5.7.5.6

**Comment by edbeeny** [comment]
OK, it seems like this is being run before the user is created and logged in.
There is also a different issue with the core which is making the issue a bit confusing.
https://github.com/mlocati/concrete5/commit/b1c9407dee4bcf86de1bc996ef1d80b98c68e60a

**Comment by brucewyne** [comment]
You're right in that I think we're doing it prematurely. I think it was because previously we were forcing "non-guest" checkouts if it contained digital downloads. Now, we create accounts on the fly. So there's some swapping we need to do here.

**Comment by brucewyne** [comment]
Got this sorted out. Will be pushing soon after testing. The entire Order class need a lot of maintenance in general.
