### ISSUE TITLE
SQL error upgrading from 3.0.1 to 3.0.1.99

### ISSUE THREAD

**Issue by tom-rice** [VividWeb/vivid_store#298]
I have just tried doing a completely fresh Concrete5 install, installed vivid_store 3.0.1, then tried to upgrade it to 3.0.1.99, this happens every time:

An exception occurred while executing 'ALTER TABLE VividStoreProductVariationOptionItems ADD CONSTRAINT FK_50D9C3734BB971ED FOREIGN KEY (poiID) REFERENCES VividStoreProductOptionItems (poiID) ON DELETE CASCADE': SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint

Are you able to reproduce this and fix/advise?

**Comment by brucewyne** [comment]
I haven't tested upgrading from 3.0.1 yet. If you're installing from git, I'd try a clean version of what's here. I just did a clean install that went well.

**Comment by brucewyne** [comment]
fixed.
