### ISSUE TITLE
Shipping Methods should be modular

### ISSUE THREAD

**Issue by brucewyne** [VividWeb/vivid_store#3]
Need to have modular shipping methods so we can throw in a lot more shipping methods and can accept 3rd party extensions

**Comment by brucewyne** [comment]
@Mesuva - Want to get your thoughts on this. I want to separate shipping into two ideas: Shipping Method, and Shipping Method Type.

**Shipping Method Type** - a type such as Flat Rate, Local Pickup, UPS, Postal Mail
**Shipping Method** - Select a shipping method type, and define it. I.e. you have multiple flat rate method types. But you can define 3 of them for Standard, Express, Next day etc..

**Comment by Mesuva** [comment]
I think your method/type thinking is very sound. Basically Shipping Methods are instances of Shipping Method Types, given a name and specific configurations. 

One Shipping Method should also be able to output multiple options in the checkout, allowing the future development of quite complex types or ones that connect with apis. 

The other little thing that would be nice is if the shipping methods defined were orderable. In ecommerce I had a few times where clients wanted extra options, but I had no nice way to order/group them after they'd been made and installed.
