### ISSUE TITLE
Image not showing when options variations are used

### ISSUE THREAD

**Issue by tom-rice** [VividWeb/vivid_store#300]
3.0.1.99 bug:
If I am using option variations, the main primary product image is no longer displayed in the vivid_product or vivid_product_list blocks, UNLESS you specify a product image for the option variation under "More options"

**Comment by brucewyne** [comment]
Should be good now :) Variants is probably the most untested thing right now. So let me know if you run into anything else.

**Comment by tom-rice** [comment]
Thanks very much for the quick fix I'll post any more bugs or fixes that I find.
