### ISSUE TITLE
Vivid Store and breadchrumbs structure "problem"

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [VividWeb/vivid_store#303]
Product name: **Graphic Photo Tee**
Category: **Clothing**
Live example: http://global.reebok.com/B85181.html

---

**99% of the times in stores you want to create this simple structure/Pattern:**
- **Category list:** In "vivid store" vivid_product_list block set to show "Clothing" category in this example. Works well :)
- **Product page:** Graphic Photo Tee

Product detials - "Good" Breadchrumbs:

> Clothing > Graphic Photo Tee

In VIVID STORE i will get this:

> product-detail > Graphic Photo Tee

**Problem: This Breadcrumbs structure dont  give the users the real site structure ("I am t-shirt and i live under Clothing category")**

---
### Solution 1 - change/set deafult page location

Mabye the solution will be to change the default page location from:
product-detail --> Product-name
To:
Store --> Category-handle-name --> Product-name
(for now i do this manually - create category page and move product under this page)

In setting mabye you can set a checkbox : "Create site tree by Categories" 
### Solution 2 - permalinks

By permalinks (i dont know very well this issue only saying) - you can set:
%category-name-handle% / %product-name
Like this WP issue for posts:
https://codex.wordpress.org/Using_Permalinks
## Better SEO (category-name > product-detail)

**This issue will also give more structure/pretty/friendly SEO links**
https://support.google.com/webmasters/answer/6001176?hl=en
http://www.pixelrush.com.au/blog/create-seo-friendly-website-structure/

---
## Really easy to create "Shop by Category" page :

If you have Tree Structure for you categories its really easy to create "Page-list" for your categories.
Page like this: https://www.thinkgeek.com/categories/

**Comment by brucewyne** [comment]
The problem of having the REAL structure determine the category is something I battled from the beginning. If you have "t-shirt" that belongs in the following categories: "new arrivals", "mens tshirts" & "athletic apparel", then where do publish the actual page? Which category does it _really_ belong to? If you say "all of them", then you have three duplicate pages. What if you want to remove it from one? Then you have a broken page. The more I see real examples in the wild, and the more I see professional stores doing what we do, I realize this is a bad practice.

We take the route of being agnostic. The shirt lives by itself and doesn't care how you want to categorize it.

To correct the bread crumbs, we will likely employ either a custom breadcrumb block or a template for the existing one. The way most professional ecommerce sites handle this is via a query string. eg.

http://yoursite.com/product-detail/t-shirt?category=New%20Arrivals 
This would produce a breadcrumb trail like Store / New Arrivals / T-shirt
whereas http://yoursite.com/product-detail/t-shirt?category=Mens%20Shirts
would produce a breadcrumb trail like Store / Mens Shirts / T-shirt

Also, if one day it's no longer part of "New Arrivals", going to that link won't break.

**Comment by Ezra-Siton-UIX** [comment]
Thanks for the quick reply.

"three duplicate pages." its something i dont think about. I think - if VIVID will solve the simple / classic / popular case (most of the time you dont put one product in more than one place in your site). Of course the same product can have topics or tags or attribute and you can show the same product in a lot of product lists.

Than Vivid VS "how to categorize"  - Sale items & "new arrivals". This issue need to be learn by reference of "real" shops and other CMS. I think even "sale-t-shirt" dont live in two spots - only under "sale".

**Sale items - ONE solution/Pattern - seperate categories -** 
In "t-shirt" i see only the t-shirt that in full price
under "sale/t-shirt" i see all the "sale" t-shirts 

Example of two "big" stores - 
**Levis:**
http://www.levi.com/US/en_US/category/men/clothing/trousers/all/_/N-1z13wzsZ8b1Z1z13x71Z1z140ojZ2s

**Holister - full price:**
https://www.hollisterco.com/webapp/wcs/stores/servlet/CategoryDisplay?storeId=11205&urlRequestType=Base&categoryId=16398&parentCategoryId=166245&catalogId=10201&langId=-1
**Holister - sale price:**
https://www.hollisterco.com/shop/wd/guys-clearance?icmp=ICT:SUM16:M:SP:H:P:CLE:SALE:Apr2

---

I will try to find more ideas for this issue.

The most complicated e-commerce i know is this (except e-bay. amazon etc). Maybe you find her ideas:
http://www.fanatics.com/

**Comment by brucewyne** [comment]
Levi's example has the products living in only one place as well. They don't have a breadcrumb to care about though.

In the end, we've made the decision to publish to one path. You may have your reasons to do otherwise, but breadcrumbs isn't a good one for our platform overall. If you want big store examples of who does this, amazon is the perfect one. Products aren't children of categories, they are associated with them. 

How we will address breadcrumbs navigation is listed above.
