### ISSUE TITLE
fID missing error when updating product

### ISSUE THREAD

**Issue by tom-rice** [VividWeb/vivid_store#304]
With latest 3.0.1.99, every time I edit a product, when I click "Update Product", I'm getting this error: The identifier fID is missing for a query of Concrete\Core\File\File

I tracked this down and discovered that I only get the error if Advanced Permissions is enabled, which enables the "File to download on purchase" option.
I think it's assuming that I have uploaded a file there, even if I don't want to use that option and had left it blank.

For now I have been able to suppress the error by:
Edit src/VividStore/Product/ProductFile.php
In the function addFilesForProduct(), at around line 66:
Find: foreach($files['dffID'] as $fileID){
Wrap everything in this foreach with this IF statement:
if ($fileID!=0) { }

Specifically, it was this line that was triggering the error, because the file object was empty:
$fs->addFileToSet($fileObj);

**Comment by brucewyne** [comment]
Thanks for reporting that. Good catch. I basically did similar. Check that it's not empty, and greater than 0.
