### ISSUE TITLE
Adding new product resets first product quantity.

### ISSUE THREAD

**Issue by Ausjorg** [VividWeb/vivid_store#305]
I have tried figuring this out but there seems to be a bug when a customer adds a second (or however many after) product to the cart. 

For replication: visit this link [https://www.occhd.org/eng/about/product-detail](https://www.occhd.org/eng/about/product-detail). Add an item to the cart and raise the quantity to whatever you want as long as it is over 1. Click update. Click continue shopping. Add another product to the cart. NOW STOP. If you look at the first products quantity it has changed back to 1. Why is that? If you keep adding products with whatever quantities you choose the first item is the only one that looses the quantity value that you have chosen.

I have tested this with all the other products as the first item and this still happens.

**Comment by brucewyne** [comment]
Good question. Which version is this? From the marketplace or the latest from here?

**Comment by Ausjorg** [comment]
This is from the marketplace and I cant seem to find a txt file that says the version. Do you know where I can find the version within any of the code files? Currently I am waiting for the person who installed this package to get back to me about the version.

**Comment by brucewyne** [comment]
I cannot recreate this issue on the current version here in GitHub. I assume it's been fixed. We'll be releasing this soon once a couple other bugs clear up.

**Comment by Ausjorg** [comment]
Sounds good. I may look through the code currently that is on github and see if we can fix our current version. We believe it is a JavaScript issue either somewhere in the update or add portion of the JS. I know this may be may be impossible to predict currently but do you have a time window of when the new version will be released to the marketplace? Just curious.

**Comment by brucewyne** [comment]
There's only a small issue left to deal with, which is the shipping clerk and how it stores numbers. So it's fairly code complete.

We also haven't checked upgrading from 3.0.1 to the current version. 

I'd say early next week. It may be a nice idea to download and upgrade based on what we have here. Maybe you'll see some bugs crop up from the upgrade that we haven't seen yet.
