### ISSUE TITLE
Cannot check out with "Invoice" payment method

### ISSUE THREAD

**Issue by tom-rice** [VividWeb/vivid_store#318]
(Using development version) I cannot complete the checkout when using the Invoice payment method. The error comes up when I select "Invoice" and click "Complete Order"

I get an Error exception in src/VividStore/Order/Order.php
Call to a member function getHandle() on a non-object 
Line 456:
StoreOrderStatusHistory::updateOrderStatusHistory($this, StoreOrderStatus::getStartingStatus()->getHandle());

This error has been there for a while, but after applying the last few days' new commits, it now seems to be suppressed by this error message instead:
"Bad Stuff happened"

**Comment by brucewyne** [comment]
yup - I left some test code in the branch. Will remove shortly.

The other error is strange though. Go to settings, make sure a "default" order status is selected. If not, select one (pending preferably), save the settings, and make sure it's still selected when you go back.

**Comment by tom-rice** [comment]
Thanks! That was exactly the problem - I had none selected. It works now.

**Comment by brucewyne** [comment]
this was also officially resolved on our end.
