### ISSUE TITLE
Latest database schema has wrong primary key name

### ISSUE THREAD

**Issue by losttheplot** [VividWeb/vivid_store#319]
Hi. I've just downloaded and installed this add-on (v.3.1.2). It looks great at first glance; really good - thanks for sharing it. However, when adding a few product attributes I then got an exception every time I tried to look at a product's details. I tracked the problem down to the primary key name of VividStoreProductAttributeValues which should be pID, not oID, so the MySQL migration/install script needs amending.

**Comment by brucewyne** [comment]
Shoot.

Thanks for catching that.
