### ISSUE TITLE
Option to choose default country

### ISSUE THREAD

**Issue by tom-rice** [VividWeb/vivid_store#326]
This one is a feature request - would be cool to have a setting to choose the default country for customer's billing/shipping address.

Right now it's hardcoded to US so I just have to remember to change US to GB in line 115 of single_pages/checkout.php and line 234 of src/VividStore/Utilities/Checkout.php

**Comment by brucewyne** [comment]
It's not hardcoded actually. It defaults to US if there's no user selected default, but you can go to Members->attributes->shipping_address and choose the default country.

**Comment by tom-rice** [comment]
Oh doy I should totally have noticed that sorry, perfect thank you!
