### ISSUE TITLE
Tax City/State doesn't always need to be required

### ISSUE THREAD

**Issue by brucewyne** [VividWeb/vivid_store#35]
Instead, it should validate based on the rules set.

**Comment by Mesuva** [comment]
My suggestion here is to remove the rule set and only require the country code.
Then the tax can match up based on how much info is added.

If you only pick a country it's a country tax.
If you pick a country and state, it's a state tax
If you pick a country, state and city, it's city tax.

Another way of saying it, is if the values configured for the tax are non-empty, they have to match the values of the customer's billing address to be applicable.
