### ISSUE TITLE
Utility link enhancements

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#36]
The utility links block would benefit from:
- Being able to show a checkout link
- Being able to show the cart total value
- Perhaps hiding if empty

**Comment by brucewyne** [comment]
I certainly like the first two.

**Comment by Mesuva** [comment]
With the last one, even if it was just something that added a class to the cart, just so it could be hidden with styles.  (those don't need to be an option then, just something like 'cartempty' when applicable)
