### ISSUE TITLE
Verify precision of money values

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#43]
With the recent tweaks I did with tax, I now think we/I should check the way values are being rounded before being inserted into the database. 

Otherwise we could have rounding on the display and during transactions, but fractions of cents stored in the order data - throwing aggregate totals off.

I think this would just be a case of ensuring that all total values are rounded to 2 decimal places before being used for transactions.

**Comment by brucewyne** [comment]
Yeah - I admittedly kind of looked at some things in here funny, and just thought I'd do a large code review before releasing 2.1 to the MP.
