### ISSUE TITLE
Callback for off-site payment processors

### ISSUE THREAD

**Issue by mnakalay** [VividWeb/vivid_store#46]
Hello,
If I want to implement an off-site payment processor like Paypal, should I wait for you to have an official callback strategy in place or should I just work something out with the payment manager's controller?

Thank you

**Comment by brucewyne** [comment]
If we do it, it won't be for a while.

**Comment by mnakalay** [comment]
ok. Sounds important though. or is it just me?

**Comment by brucewyne** [comment]
I'm a little biased, but not alone, when I say I hate paypal. But the importance of having paypal is having a cheap/free payment gateway that works internationally. I personally think Stripe, which is offered as an extension, does that job better and covers much of europe + some.

So supporting paypal is further down my list. If you have interest in developing a paypal extension, and need to hack at the core to do so I'd be happy to merge in a PR.

**Comment by mnakalay** [comment]
You're preaching to a convinced crowd here I think. I love Stripe and hate Paypal.
However...
1 - Not everybody has access to Stripe. Do you know how big Concrete5 is in Japan? They don't have access to Stripe. I live in North Africa and nobody in Africa has access to Stripe.
2- For the average user I really think not offering Paypal is a deal breaker and now you have other free ecommerce add-ons waiting to go through the PRB. A guy posted an adaptation of Wordpress Woocommerce.
3- Paypal is not the only off-site payment processor. I think a callback something really needs to happen.

I'll try to see if I can cook something up with the core and send a pull request

**Comment by brucewyne** [comment]
I'm with you on this, and I realize things like 2checkout etc are also very popular. I'm on board, just lower on my list of priorities. If you're interested in tackling this, I can go ahead and mark this as in development. 

I'm sorry I sounded dismissive before. I just immediately roll my eyes when I hear paypal. It's just a reflex :)

**Comment by mnakalay** [comment]
You definitely didn't sound dismissive and I feel the way you do about Paypal. But I also know it is pretty much a developer bias and for the final user, this debate doesn't have the same value.

Stripe is a developer wet dream but frankly I have never met a customer that knew of it and didn't need convincing.

AND for the client, it can be costlier to implement.

I am going to work on this on my spare time but to be honest I don't have much so marking it officially in development might be a little premature. I wouldn't want to let you down.

**Comment by brucewyne** [comment]
Yeah, I understand for sure.

I'll give you a three week head start. We have a lot we want to do over that time (coupons/shipping) etc.. So once we're done with that, we'll see where you or someone else is with this. If it hasn't been done yet, we'll tackle it :)

**Comment by edbeeny** [comment]
@mnakalay did you start looking into this? I have a couple of clients who only use paypal.

**Comment by mnakalay** [comment]
No Sorry I didn't get a chance but I think, for now, might be easier to implement your own callback rather that try to make it a core thing

**Comment by brucewyne** [comment]
I'm going to try and get to this later this week. Marking as in development.

**Comment by edbeeny** [comment]
Thanks for the update.

**Comment by Bloodb0ne** [comment]
I made an implementation of PayPal payment method and the method i used was to create custom routes. I redirect in the payment method function and the return URL is to a custom route. In the custom route i mock the submit.
This is inside the function called by the route:

```
$_POST['payment_method'] = 'payment_method_handle';
Checkout::submit();
```

The other problem i had was that PayPal needs a invoice id or some kind of identifier for the verification and the order gets created after the payment completion.Which was fixed using a separate table that creates a cartID and maps it to the order when its completed.

**Comment by brucewyne** [comment]
@Bloodb0ne - did you do this for this store? Or something else? If former, would you mind sharing that code?

**Comment by Bloodb0ne** [comment]
Yes its for this store https://github.com/Bloodb0ne/Concrete5_DevRepo/tree/master/paypal_express_vivid_store

**Comment by brucewyne** [comment]
Too bad it's invoicing rather than directly taking people offsite to paypal before completing the order. We're going to be wrapping up what we've been working on shortly with paypal. We'll have that integrated into the store by default.

**Comment by brucewyne** [comment]
That said to address the original question, @mnakalay, because offsite processors are so varied, I think we're going to rely on routes set in the package of the gateway rather than a standard that I think would be too hard to keep up with and constantly modify.

There's a couple things we're doing though such as a flag for offsite gateways so that the order doesn't get completed, but rather let the gateway callback submit it. Still a few things to work out, but we'll have a good example for it soon once we finish PayPal

**Comment by brucewyne** [comment]
PayPal is done. Will be in the MP shortly.
