### ISSUE TITLE
5.7.4 unable to install

### ISSUE THREAD

**Issue by erik-maas** [VividWeb/vivid_store#49]
So, The store is not able to install on Concrete5.7.4.
The error in the log is:
Exception Occurred: /home/admin/domains/devyou.nl/public_html/574/packages/vivid_store/src/VividStore/Payment/Methods/auth_net/anet_php_sdk/lib/AuthorizeNetTD.php:19 Class 'AuthorizeNetRequest' not found (1)

Even when disabling the auth_net install line in the package controller it breaks on this error.

This is only the case on 5.7.4
5.7.3.1 is installing as aspected for me.

**Comment by brucewyne** [comment]
Yeah - there's some fixes here in git for that, they just need to be released. Was hoping a few more things would make it into that release. We'll try to push something out today.
