### ISSUE TITLE
Zip code validation shouldn't check for minimum characters 

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#5]
I believe some places in the world have zip codes shorter than 4 characters, or none at all. 
So the minimum character check probably should be taken off the zip code (or only applied for certain countries)

**Comment by brucewyne** [comment]
I feel like it'd be pretty unwise to just let it be blank. But yes, there are countries without zip codes. I found some decent zip code validators available online based on the country code. Maybe if we can get a fairly complete definition list and then ignore what we don't know...

**Comment by Mesuva** [comment]
I reckon just validate to not empty. Someone with a two digit zip code is going to have trouble with a 4 digital minimum, but if it was simply that it need to be non-empty, someone without a zip code could at least put NA or a dash or something. No need for a complex validator at this stage.

**Comment by Mesuva** [comment]
I've realised I've changed this as part of my guest checkin pull request. I also changed the error messages to use the same language as the fields on the form (Postal Code, not Zip code... Postal Code is bit more international anyway).

**Comment by Mesuva** [comment]
This one can be closed I believe
