### ISSUE TITLE
Updating the setting generates :unexpected error (String)"

### ISSUE THREAD

**Issue by 66shayan** [VividWeb/vivid_store#64]
Hey there, first i would say a big thanks to you for developing the free commerce madule! its really great.

my issue is i cant update the setting at all, to put my local currency symbol etc. its just saying this everytime i want to update the setting:

An exception occurred while executing 'SELECT osID FROM VividStoreOrderStatus WHERE osHandle=?' with params [{"error":"","osIsStartingStatus":null}]: Object of class Concrete\Package\VividStore\src\VividStore\Orders\OrderStatus\OrderStatus could not be converted to string

please help :)

**Comment by brucewyne** [comment]
I think there was/is an error that the default order status wasn't set. Try going to the status tab, set a default then save. Hopefully that should resolve your immediate issue. If that works, report back :)

**Comment by 66shayan** [comment]
Works great, thank you so much!

**Comment by brucewyne** [comment]
@skybluesofa is there a fix for this somewhere I didn't see? Have you seen this?

**Comment by skybluesofa** [comment]
I'm sorry, I didn't see it.

One thing I did notice is that the table the SQL is pulling from is singular, 'VividStoreOrderStatus'. Perhaps the issue was some old code? I haven't been able to recreate the issue.
