### ISSUE TITLE
'Tax already included in price' option

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#7]
In Australialand we generally display product prices including tax (GST) and don't add them in the checkout, we simple display it as a summary in the totals/receipts.  

So it would be great to be able to show and record the tax applicable to an order, but for prices where it has already been applied.

**Comment by skybluesofa** [comment]
Mesuva, how does it work? Lets take 10% tax as an example.
- Enter an item price of $30 and the tax is worked out backwards: $3, or
- Enter an item price of $27 and the tax is added to the price when shown in the UI, or 
- Something else?

**Comment by Mesuva** [comment]
The first one, the tax is assumed to be already in the price, so the tax that is in it already is calculated and displayed.

You're maths wouldn't be right though for 10% though, it's 1/11 of the price. The tax would be $2.72, and the ex-GST price would be $27.28.  :-)

**Comment by brucewyne** [comment]
This is pretty simple to do. We (vivid) could probably knock this out this week once we're done with the shipping method stuff.

**Comment by brucewyne** [comment]
unless someone wants to tackle it sooner. Doesn't matter to me :)
