### ISSUE TITLE
Exclude shipping related questions in checkout if there are no shippable products in cart

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#72]
Subject says it all really. Pretty sure this wouldn't be hard to implement, I'd see it as:
- Some function in Cart.php that returns whether the cart contains any shipable items
- Some conditional statements in the checkout single page
- Probably some modifications to prevent validation from kicking in or other issues about not having a shipping address when displaying ordering (emails, dashboard summaries, etc)

**Comment by brucewyne** [comment]
There's some exceptions to this I'd like to discuss. A digital good, depending on the state, is taxable. In all of those same states, tax is based on the shipping address, even though nothing is actually being shipped. It's all about the person receiving the product.

Just thinking of odd scenarios.

**Comment by erik-maas** [comment]
Also, When you want to pickup goods instead of shipping. Should the shipping address be provided?

When tax depends on shipping, we could change it to base it on shipping, with a fallback to the invoice address.

**Comment by Mesuva** [comment]
I agree with companyyou that in the case of a digital good being taxable, it should simply fall back to working out the taxes based on the billing address. In that case billing address is really just 'address'.

In the case of picking up goods, the offer to pick up the item would be provided by a shipping option. I think it would still ask for a shipping address, as there is still the chance of needing to ship the item if circumstances change.

My point with this issue is really in the case of digital only products, cases where even the word 'Shipping' itself is meaningless - I just think there needs to be way to make it a billing address only, in the same way as eCommerce skips the shipping screen if there are not shippable items (that works great).
