### ISSUE TITLE
nested groups

### ISSUE THREAD

**Issue by Remo** [VividWeb/vivid_store#76]
I think it won't take long till some users will want to nest groups. I think we could create the nested structure with pages and then select the right group, but that will cause a lot of annoying manual work.

The store solution we've worked with had the ability to create pages based on categories (groups in your case) with support for unlimited levels.

**Comment by brucewyne** [comment]
Yeah - this was started as a discussion in issue #12 with addition of the fact that it's silly that each product can currently only be a part of one group.
