### ISSUE TITLE
shipping cost calculation

### ISSUE THREAD

**Issue by Remo** [VividWeb/vivid_store#78]
I think we need more flexibility to calculate shipping costs. Here are some ideas takes from past projects:
- Country specific shipping costs
- Non-linear prices
- They should optionally have VAT. The global setting we currently have won't cover all situations as shipping can be done through a company charging you VAT and VAT free delivery
- There should be a minimum and maximum amount / weight / dimension per shipping method as not all methods make sense
- Additional cost should be absolute or relative (fix amount vs. percentage)

Here's a badly translated screenshot from our old system.

Please note that we've created geo-zones to avoid the necessity to select all the EU countries in various places throughout the store. A ge zones is nothing but a collection of countries.

![image](https://cloud.githubusercontent.com/assets/129864/8006348/31f48876-0b93-11e5-9c83-a22d9e15359e.png)

**Comment by brucewyne** [comment]
Yup - shipping sucks right now. That is a bit ticket item I'm currently working on to make modular in general to plug in different shipping types.

You bring up a good point about maximum weight for a shipping method. It just donned on me that obviously (for US especially) that the post office won't take anything over like 60 pounds or something. At that point, we rely on FedEx/UPS.

**Comment by brucewyne** [comment]
Also, here's some additional discussion on my thoughts on setting up shipping #3

**Comment by brucewyne** [comment]
@Remo This is nearly there now with the latest push (which you should check out). It's still missing weight restrictions. That said, that will be fairly easy to add. 

Check out the FlatRateShippingMethod class, there's two important methods, isEligible() and getRate(). isEligible() is where you can determine your own logic of whether the cart is eligible for the shipping method. This could be anything from the weight of the cart, to the country their in, quantity...whatever.

On my to-do is to add a method to the Cart class to deliver the weight. Though there's enough provided technically that you could figure that out.

**Comment by brucewyne** [comment]
@remo can you school me in shipping with VAT? If you're a company that charges VAT on shipping, I assume you do so on all shipping methods. If that's the case, do the tax options available not work? They allow you to charge tax based on subtotal, or subtotal+shipping.

**Comment by brucewyne** [comment]
donesies.

**Comment by Remo** [comment]
@brucewyne I'm by no means a VAT expert, it was actually the topic where I've got my worst grades ;-) One example, the part I believe is the most complex: Since the beginning of the year the EU has changes their law in a way where you must pay the rate of the country of your customer.

> This means for example that your Dutch company will need to pay 21% Dutch VAT for the fees collected from your Dutch private customers, 25% Swedish VAT from your Swedish private customers and 19% German VAT from your German customers, etc.
> (http://www.foreigninvestments.eu/en/fdi/expert-topics/change-in-european-union-vat-rules-per-1-january-2015-for-telecommunications-broadcasting-and-electronic-services)

It's a bit different in Switzerland, he you either don't add VAT or add 2.5% or 8% depending on the kind of goods/sevices you're offering. Funny thing though is the fact that the VAT law defines the country of Switzerland in a slightly different way than everyone else. That's something I'd ignore for now though as it goes a bit too far - I assume other countries have such strange laws too.

**Comment by brucewyne** [comment]
I made it so it was pretty much that flexible and then realized I should probably take it the next step and make Tax Classes. Allowing the ability to group tax rates, and those tax rates could be applied to certain products.

**Comment by Remo** [comment]
Yes but those tax rates would have to depend on the country you select during the checkout too!

**Comment by brucewyne** [comment]
Yes - Each tax rate would allow you to pretty much select when to charge those rates. It's setup as a multiple version of the previous tax rate options. 

So each time you add a tax rate, you can choose how you'd like to total the tax rates (pre or post shipping), if the customers shipping or billing address match which country etc etc...

Then the idea is you could group those into a class. Despite whether a product is associated with a certain tax class or not, it would be up to the Tax Rate settings to determine whether to actually charge tax or not.
