### ISSUE TITLE
Order status history

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#8]
When an order status changes it's often handy to have this recorded with a date, basically a log. This allows an order history to be displayed on an order summary screen.
- Order Placed 17 April, 2015
- Order changed to 'Paid' 18 April, 2015
- Order changed to 'Shipped' 18 April, 2015

**Comment by brucewyne** [comment]
speaking of this - I kind of would like to have the status options available to be configured in the settings.

**Comment by skybluesofa** [comment]
I'm working on this. I've created the dashboard functionality, now working on the history functionality.

How can I tag that I'm working on it?

**Comment by brucewyne** [comment]
@skybluesofa Killer! I've marked it as in development.
