### ISSUE TITLE
stock quantity and additional price per product option

### ISSUE THREAD

**Issue by Remo** [VividWeb/vivid_store#80]
I'm comparing our ancient solution with yours and noticed another requirement we've had in the past. Not often but it was needed. On our case product options where handled by a special attribute.

It had three fields:
- Option = Option name
- Lagerbestand = Stock quantity
- Mehrpreis = additional price (the XXL shirt is sometimes more expensive than the XXS one)

![image](https://cloud.githubusercontent.com/assets/129864/8006826/6bfe4418-0b97-11e5-93bd-f23b473248fb.png)

Might partially be related to https://github.com/VividWeb/vivid_store/issues/31

**Comment by brucewyne** [comment]
yes. So, I found the best comparable of how I'd LIKE this to be is in shopify. For each option, you can leave it simple as is, or break it out into a matrix where option 1 + option 2 = different sku, qty, price.

For example, keeping track of a small blue shirt vs an xxl green shirt.

**Comment by Remo** [comment]
That would be awesome but I gave up on that because we didn't have enough resources to get it done. We ended up having just one text field to describe the whole option. Matrix would be much better though!

**Comment by brucewyne** [comment]
Haha yeah - it's certainly going to take some muscle. But it's just the only way to do it if we're going to do it.

**Comment by erik-maas** [comment]
Wouldn't it be easier to create a parent-children product type?
That way you can have the power of full product editing, and if something is different in a product (like limited XXXL t-shirt colours).

Would that be easier to use then a creating the option matrix?

**Comment by Remo** [comment]
That approach would depend a lot on the UI, if it were two separate products with different attributes it would be pretty much a no-go for me as it would get really messy. I'd want to see all options (sub-products) in the main product at once to get a nice overview and I'd probably want to be able to edit all sub-products from the main product.

I see how this could work, but it would go against the options we currently have.

**Comment by erik-maas** [comment]
It could be a special child-product.
The product attributes would be managed from the main product.  But you can limit the options in the child product.

So, from colors, i want to show blue, green and black. But not white and yellow.
You can also integrate this product in discount codes (so for christmas, you give 10% discount on all red XL+ shirts) for instance.

You can also display these products on there own in the front. For example if you have a special page just with XXL+ shirts. Or as a single product.

**Comment by Remo** [comment]
Well, before we go there we should probably about what I've mentioned here https://github.com/VividWeb/vivid_store/issues/74

That would be the base of such child-products too..

**Comment by 978bobs** [comment]
Just picking up this thread.  There are lots of ways to think about this.  My suggestion is to tackle the easiest one first and create a roadmap that either allows for paid addons for higher value features or at least user-funded add-ons as users will require on-going enhancements.

Product Options:  I have a T-Shirt printed.  Base price is without custom text.  Option for the product to add up to 25 letters = +2.00 to the base price.  This adds ties back to tier prices.  If you are buying 10 or more items you add +2.00 to the tier price.  This can be configured at the item SKU by default feature.  [THIS IS A FIRST RELEASE FEATURE] Later on you can create an OPTION class that can apply across many SKUs simultaneously. [THIS IS A LATER FEATURE OR EVEN PAID ENHANCEMENT - just prepare the code for it's eventual deployment]

Bill of Materials:  Here if you have a computer and you decide to add a MONITOR, KEYBOARD, AND SOFTWARE.  You will want to manage these as individual SKUs or COMPONENT-SKUs so you can price accordingly.  Plus these Component-SKUs can be priced seperately. [LATER FEATURE or COMMUNITY EFFORT]

Matrix Product:  This is the classic STYLE, SIZE, COLOR where a business actually tracks inventory at each point in the matrix and would want to potentially price within the matrix as well.  This feature set is critical in ecommerce retail but when poorly designed and executed will cause all sorts of pain.  [PAID ADD-ON ENHANCEMENT]

**Comment by 978bobs** [comment]
For Product Options, a single option selection might have multiple choices.  Shirt might have a Sleeve/T-Shirt Option, a Size Option, and a Graphic/No-Graphic option.  Each choice would have a SKU-modifier as a suffix.  So original sku ABC is modified to ABC-1A when the first option choice selects A.  If the user selects multiple options the sku is modified to ABC-1A-2C-3J.  More importantly the shopping cart/line-item has multiple lines of additional descriptive text to convey the full meaning of what was ordered.

**Comment by 978bobs** [comment]
I took a closer look at the requirement I have...

Each has
HEADER INFO***
Label which is customizable and renders in the front end
Has an input type such as [TEXT FIELD, TEXT AREA, FILE, DROPDOWN, RADIO BUTTONS, CHECKBOX, MULTISELECT, DATE, DATE-TIME, ETC]
REQUIRED FLAG Y/N
SORT ORDER (to allow for multiple options to be reordered)

CHILD INFO***can have multiples
TITLE of the option for example if dropdown
PRICE can be entered as decimal value
PRICETYPE  applied to the base/tier price as fixed or percent
SKU which appends to the base sku
MAX CHARACTERS
SORT ORDER for order they appear in the dropdown
