### ISSUE TITLE
Customer can order more than quantity available

### ISSUE THREAD

**Issue by brucewyne** [VividWeb/vivid_store#84]
Not necessarily a bug, but may be unexpected for some.

I'd like to address this with additional settings (not sure if per product or global).

Things to consider
- Allow purchase of out of stock items
- Cap quantity in cart to what is available (can't purchase 6 of something if only 5 are in stock, show a message, reset their qty to 5)
- Hide out of stock products from product list?
- Show "out of stock" label on detail page and/or product list?

**Comment by Mesuva** [comment]
I think this would relate to one of my pull requests you merged the other day.
When something is added to the cart it now returns some json data (and exits to avoid a full page request).

I'm thinking in that return data there could be messages or errors, that a cart overlay can display.

**Comment by brucewyne** [comment]
Here's some things I think should go into this.
- Add/Edit Product screen should have a checkbox to allow for negative quantities. By default this will be unchecked.
- If they enter an amount more than the quantity available, alert them, and set the quantity to the max available.
- Product List block should have a new option whether to show products that are in stock or not. Default to no.
- If out of stock, Product Block, Product List, and Product Modal need to remove their add to cart buttons and have a label about being out of stock.
