### ISSUE TITLE
use Config; causes errors pre 7.4

### ISSUE THREAD

**Issue by brucewyne** [VividWeb/vivid_store#87]
In 5.7.3 use Config does not work. it needs the full namespace.

**Comment by Mesuva** [comment]
I'm pretty certain I was just going 'use Config;' in packages for 5.7.3, where's this showing up?

**Comment by Mesuva** [comment]
If this is 5.7.3 only, I'd say close this issue - no-one should be running 5.7.3!

**Comment by brucewyne** [comment]
Yeah - I'm closing this. I think when I looked into it it wasn't even related to that.
