### ISSUE TITLE
Auth.net User errors.

### ISSUE THREAD

**Issue by DevScarabyte** [VividWeb/vivid_store#91]
Checking if anyone else is having issues with this.

The use statement with non-compound name 'AuthorizeNetRequest' has no effect.

In the Root namespace there is no need to have a use, and since the Auth.net libs don't use namespaces there is really no point.

Fix is to remove the uses.

**Comment by brucewyne** [comment]
This has been addressed and we replaced authnet with a PSR friendly version of it.
