### ISSUE TITLE
Subtotal price is incorrect

### ISSUE THREAD

**Issue by Rgeelen** [VividWeb/vivid_store#93]
Something seems to be going wrong when the subtotal of the order and order item is calculated. 
## Currency settings

Symbol: €
Thousands Separator e.g. , or a space: . (period)
Whole Number Separator e.g. period or a comma: , (comma)

The actual price of the product is: 1400,00
## Order items (info)

Price on the order: 14.000,00
Quantity: 1
Subtotal: €1.400.000.000,00

Items Subtotal: €140.000,00
Tax: €0,00
Total: €1.400,00
![screen shot 2015-07-21 at 12 27 48](https://cloud.githubusercontent.com/assets/4224426/8798716/a81e20d6-2fa4-11e5-84f5-9a5bdd8fe104.png)

**Comment by brucewyne** [comment]
Thanks for catching that. I imagine it's not liking the formatting somewhere. Could you try it with the . and , reversed (like US) just to double check?

**Comment by Rgeelen** [comment]
The problem only occurs when it is not like the US format. The oiPricePaid is stored as 140000.0000
I think the price should be inserted in the db unformatted. Only when displaying we should format the price.
